version: "3"
services:
   node:
      build:
         context: .
         dockerfile: Dockerfile
      stdin_open: true
      tty: true
      command: gatsby develop -H 0.0.0.0
      ports:
         - "3000:8000"
      volumes:
         - ./src:/app/src
