version: "3.8"

services:
   api:
      build: .
      command: npm run dev
      volumes:
         - ./src:/app/src
         - ./dist:/app/dist
      ports:
         - 4200:3000
      networks:
         - local-mysql
networks:
   local-mysql:
      external: true
